version: "3.9"
services:
  todo-db-flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://todo-api-db -schemas=todo -user=todo_user -password=db_pass -connectRetries=60 migrate
    volumes:
      - .\db:/flyway/sql
    depends_on:
      - todo-api-db
  todo-api-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: db_pass
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root_db_pass
  todo-api-application:
    image: couryrr/todo-api:latest
    restart: always
    depends_on:
      - todo-db-flyway
      - todo-api-db
    ports:
      - "9999:80"
    environment:
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: db_pass
      MYSQL_DATABASE: todo
networks:
  default:
    name: todo-api-net
